### ISSUE TITLE
services.html #2

### ISSUE THREAD

**Issue by taylorculver** [taylorculver/xenodatapartners.com#10]
@cknific I really like the aesthetics of the "Areas of Focus" grid! Can we reformat it so it appears the same on the production website? Minor change.

**DEV**
<img width="1216" alt="screen shot 2018-05-24 at 9 29 18 pm" src="https://user-images.githubusercontent.com/11591628/40526693-35a1aab0-5fb6-11e8-8209-8d400157e5a1.png">

**PROD**
<img width="1230" alt="screen shot 2018-05-25 at 12 53 24 am" src="https://user-images.githubusercontent.com/11591628/40526702-4149f200-5fb6-11e8-923b-86c345ec06ec.png">

**Comment by cknific** [comment]
https://github.com/taylorculver/xenodatapartners.com/pull/11
