### ISSUE TITLE
D3.js

### ISSUE THREAD

**Issue by taylorculver** [taylorculver/xenodatapartners.com#14]
@cknific - could we make the D3.js on the index.html page responsive?

**Comment by cknific** [comment]
@taylorculver I have this on my radar. I can take a look next week when i’m back at the office.

**Comment by taylorculver** [comment]
thanks @cknific - appreciate the help. Enjoy your PTO.

**Comment by cknific** [comment]
@taylorculver I have the app running locally with docker (thanks @phlipper) and can now see the d3 visualizations. I'll get them looking nice on mobile now 😃. Sorry for the delay!

**Comment by taylorculver** [comment]
@cknific - any luck?

**Comment by cknific** [comment]
@taylorculver working on this today!

**Comment by cknific** [comment]
@taylorculver there are a lot of hardcoded widths and heights within each of the d3 html files (visualizations.html and bubbles.html), so this isn't as simple as a CSS change, unfortunately. We know what we need to do, and it will take a few hours.

Can you please add our partner `dannyb` to this github repo? He'll be pushing up some code for this.

**Comment by cknific** [comment]
@taylorculver thanks for adding Danny. We've made good progress on this, and we expect to tweak the UI and get a PR up today.

**Comment by taylorculver** [comment]
Thanks for the update @cknific

**Comment by cknific** [comment]
#16

**Comment by cknific** [comment]
@taylorculver we have this working in PR #16. The charts respond to the widths of the browser. There are a lot of folks out there who take things a step further in altering the display of the graphs as the size of their containers change (e.g. display fewer items on the Y axis under a certain height). [This](https://blog.webkid.io/responsive-chart-usability-d3/) is a good example of such an undertaking.

So, when you test this out. Keep in mind there can be more done. 😄
